trigger:
  none

pool:
  name: "Comp367_SH_Agent"

variables:
  projectName: 'BudgetManagementAPI'
  testProject: 'BudgetManagementAPI.Tests'
  dockerHubRepo: 'yourdockerhubusername/budgetmanagement-api'
  dockerfilePath: 'BudgetManagementAPI/Dockerfile'
  shortSha: $[format('{0}', variables['Build.SourceVersion'].Substring(0, 7))]

stages:
- stage: SonarQubeAnalysis
  displayName: Code Analysis and Coverage
  jobs:
  - job: Analysis
    displayName: Run SonarQube with Code Coverage
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x.x'

    - script: dotnet restore $(projectName)/$(projectName).csproj
      displayName: 'Restore Dependencies'

    - script: dotnet build $(projectName)/$(projectName).csproj --no-incremental
      displayName: 'Build Project'

    - script: |
        dotnet test $(testProject)/$(testProject).csproj \
          /p:CollectCoverage=true \
          /p:CoverletOutputFormat=opencover \
          /p:CoverletOutput=./TestResults/coverage.opencover.xml
      displayName: 'Run Tests with Coverage'
    - task: SonarQubePrepare@7
      inputs:
        SonarQube: 'manual'
        scannerMode: 'dotnet'
        #configMode: 'manual'
        serverUrl: 'http://localhost:9000'
        token: '$(SONAR_TOKEN)'
        extraProperties: |
          sonar.projectKey=$(projectName)
          sonar.cs.opencover.reportsPaths=$(testProject)/TestResults/coverage.opencover.xml

    - task: SonarQubeAnalyze@7
      displayName: 'Run SonarQube Analysis'

    - task: SonarQubePublish@7
      inputs:
        pollingTimeoutSec: '300'
      displayName: 'Publish SonarQube Report'


- stage: BuildAndPush
  displayName: Build & Push Docker Image
  dependsOn: SonarQubeAnalysis
  jobs:
  - job: DockerBuildPush
    displayName: Build and Push Docker Image
    steps:
    - task: Docker@2
      displayName: 'Login to Docker Hub'
      inputs:
        command: login
        containerRegistry: ''
        username: '$(DOCKER_USERNAME)'
        password: '$(DOCKER_PASSWORD)'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        Dockerfile: $(dockerfilePath)
        tags: |
          $(dockerHubRepo):latest
          $(dockerHubRepo):$(shortSha)

    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: push
        tags: |
          $(dockerHubRepo):latest
          $(dockerHubRepo):$(shortSha)
